quarkus:
  http:
    port: 3041
  log:
    level: INFO

mp:
  messaging:

    # MQTT
    incoming:
      rtl433-in:
        connector: smallrye-mqtt
        host: ${INCOMING_MQTT_HOST}
        port: ${INCOMING_MQTT_PORT:1883}
        topic: rtl_433/c1f2d7d5512c/events
        qos: 1
        client-id: rtl433-client
        auto-acknowledge: true
        broadcast: true

    # RabbitMQ
    outgoing:
      raw-message:
        connector: smallrye-rabbitmq
        exchange: raw-message-exchange
        exchange-type: topic
        routing-key: raw.data
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_CLIENT_USERNAME}
        password: ${RABBITMQ_CLIENT_PASSWORD}
