quarkus:
  http:
    port: 3041
  log:
    level: INFO

mp:
  messaging:

    # MQTT
    incoming:
      rtl433-in:
        connector: smallrye-mqtt
        host: ${INCOMING_MQTT_HOST:10.10.30.23}
        port: ${INCOMING_MQTT_PORT:1883}
        topic: rtl_433/c1f2d7d5512c/events
        qos: 1
        client-id: rtl433-client
        auto-acknowledge: true

    # RabbitMQ
    outgoing:
      raw-message:
        connector: smallrye-rabbitmq
        exchange: raw-message-exchange
        exchange-type: topic
        routing-key: raw.data
        host: ${OUTGOING_RABBITMQ_HOST:localhost}
        port: ${OUTGOING_RABBITMQ_PORT:5672}
        username: ${OUTGOING_RABBITMQ_USERNAME:admin}
        password: ${OUTGOING_RABBITMQ_PASSWORD:secret}
