quarkus:
  http:
    port: 3043
  log:
    level: INFO

mp:
  messaging:

    # RabbitMQ
    incoming:
      raw-message:
        connector: smallrye-rabbitmq
        queue: recommendation-queue
        exchange: raw-message-exchange
        exchange-type: topic
        routing-key: raw.#
        auto-bind-exchange: true
        declare: true
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_CLIENT_USERNAME}
        password: ${RABBITMQ_CLIENT_PASSWORD}
