quarkus:

  http:
    port: 3042

  log:
    level: INFO

  mongodb:
    connection-string: mongodb://admin:secret@localhost:27017/taskdb?authSource=admin
    database: quarkus-device-data-pipeline

mp:
  messaging:

    # RabbitMQ
    incoming:
      raw-message:
        connector: smallrye-rabbitmq
        queue: model-queue
        exchange: raw-message-exchange
        exchange-type: topic
        routing-key: raw.#
        auto-bind-exchange: true
        declare: true
        host: localhost
        port: 5672
        username: admin
        password: secret
