services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
    secrets:
      - rabbitmq_admin_username
      - rabbitmq_admin_password
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/outgoing_rabbitmq_username
      RABBITMQ_DEFAULT_PASS_FILE: secret

  ingester-ms:
    container_name: ingester-ms
    image: brulejr/ingester-ms:latest
    ports:
      - "3041:3041"
    secrets:
      - incoming_mqtt_host
      - incoming_mqtt_port
      - rabbitmq_client_username
      - rabbitmq_client_password
    environment:
      PROFILE: "prod"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./config:config/app:ro

secrets:
  incoming_mqtt_host:
    file: secrets/incoming_mqtt_host.txt
  incoming_mqtt_port:
    file: secrets/incoming_mqtt_port.txt
  mongo_username:
    file: secrets/mongo_username.txt
  mongo_password:
    file: secrets/mongo_password.txt
  rabbitmq_admin_username:
    file: secrets/rabbitmq_admin_username.txt
  rabbitmq_admin_password:
    file: secrets/rabbitmq_admin_password.txt
  rabbitmq_client_username:
    file: secrets/rabbitmq_client_username.txt
  rabbitmq_client_password:
    file: secrets/rabbitmq_client_password.txt

volumes:
  rabbitmq_data:
  rabbitmq_logs:
